development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

# Configure the database connection
set :database_file, 'config/database.yml'

# Enable sessions
enable :sessions
